markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : PeedleCode
production_url : http://craigchristenson.github.com
description:
disqus_shortname: peedlecode
analytics: 
gauges: 
author :
  name : Craig Christenson
  github : craigchristenson
  twitter : 
  email: christensoncraig@gmail.com
