markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : PeedleCOde
production_url : http://carlosbecker.com
description: "My Blog."
disqus_shortname: peedlecode
analytics: 
gauges: 
author :
  name : Craig Christenson
  github : craigchristenson
  twitter : peedlecode
  email: peedlecode@gmail.com
